NAME_TO_TICK_DICT = {
    "Microsoft Corp.": "MSFT",
    "Accenture PLC": "ACN",
    "Adobe Inc.": "ADBE",
    "Automatic Data Processing Inc.": "ADP",
    "Fidelity National Information Services Inc.": "FIS",
    "Fiserv Inc.": "FISV",
    "International Business Machines Corp.": "IBM",
    "Intuit Inc.": "INTU",
    "Mastercard Inc.": "MA",
    "Oracle Corp.": "ORCL",
    "PayPal Holdings Inc.": "PYPL",
    "salesforce.com inc.": "CRM",
    "ServiceNow Inc.": "NOW",
    "Visa Inc.": "V",
}

company_list_nyse = [
    "3M-Co",
    "Abbott-Laboratories",
    "AbbVie-Inc",
    "Accenture-PLC",
    "Altria-Group-Inc",
    "Anthem-Inc",
    "ATT-Inc",
    "Boeing-Co",
    "Bristol-Myers-Squibb-Co",
    "Caterpillar-Inc",
    "Chevron-Corp",
    "Coca-Cola-Co",
    "Colgate-Palmolive-Co",
    "ConocoPhillips",
    "CVS-Health-Corp",
    "Danaher-Corp",
    "Delta-Air-Lines-Inc",
    "Devon-Energy-Corp",
    "Eli-Lilly-Co",
    "Exxon-Mobil-Corp",
    "FedEx-Corp",
    "Ford-Motor-Co",
    "GameStop-Corp",
    "General-Electric-Co",
    "General-Motors-Co",
    "HCA-Healthcare-Inc",
    "Home-Depot-Inc",
    "International-Business-Machines-Corp",
    "Johnson-Johnson",
    "Linde-plc",
    "Lockheed-Martin-Corp",
    "Lowes-Cos-Inc",
    "Mastercard-Inc",
    "McDonalds-Corp",
    "Medtronic-PLC",
    "Merck-Co-Inc",
    "Mosaic-Co",
    "Nike-Inc",
    "Occidental-Petroleum-Corp",
    "Oracle-Corp",
    "Pfizer-Inc",
    "Philip-Morris-International-Inc",
    "Procter-Gamble-Co",
    "Raytheon-Technologies-Corp",
    "Salesforce-Inc",
    "ServiceNow-Inc",
    "Sherwin-Williams-Co",
    "Target-Corp",
    "Thermo-Fisher-Scientific-Inc",
    "TJX-Cos-Inc",
    "Twitter-Inc",
    "Union-Pacific-Corp",
    "United-Parcel-Service-Inc",
    "UnitedHealth-Group-Inc",
    "Valero-Energy-Corp",
    "Verizon-Communications-Inc",
    "Visa-Inc",
    "Walmart-Inc",
    "Walt-Disney-Co",
    "Zoetis-Inc"
]

company_list_nasdaq = [
    "Adobe-Inc",
    "Advanced-Micro-Devices-Inc",
    "Alphabet-Inc",
    "Amazoncom-Inc",
    "American-Airlines-Group-Inc",
    "Amgen-Inc",
    "Analog-Devices-Inc",
    "Apple-Inc",
    "Applied-Materials-Inc",
    "Automatic-Data-Processing-Inc",
    "Booking-Holdings-Inc",
    "Broadcom-Inc",
    "Charter-Communications-Inc",
    "Cisco-Systems-Inc",
    "Comcast-Corp",
    "Costco-Wholesale-Corp",
    "CSX-Corp",
    "Expedia-Group-Inc",
    "Gilead-Sciences-Inc",
    "Honeywell-International-Inc",
    "Intel-Corp",
    "Intuit-Inc",
    "Intuitive-Surgical-Inc",
    "Lam-Research-Corp",
    "Meta-Platforms-Inc",
    "Micron-Technology-Inc",
    "Microsoft-Corp",
    "Moderna-Inc",
    "Mondelez-International-Inc",
    "Netflix-Inc",
    "NVIDIA-Corp",
    "PayPal-Holdings-Inc",
    "PepsiCo-Inc",
    "Qualcomm-Inc",
    "Regeneron-Pharmaceuticals-Inc",
    "Starbucks-Corp",
    "T-Mobile-US-Inc",
    "Tesla-Inc",
    "United-Airlines-Holdings-Inc",
    "Texas-Instruments-Inc"
]

file_list = [
    "Current-Ratio.xlsx",
    "Debt-to-Assets.xlsx",
    "Financial-Leverage.xlsx",
    "Operating-Profit-Margin.xlsx",
    "Receivables-Turnover.xlsx",
    "Total-Asset-Turnover.xlsx",
    # "Net-Fixed-Asset-Turnover.xlsx",
    # "ROE.xlsx",
    # "Net-Profit-Margin.xlsx",
    "Debt-to-Equity.xlsx",
    "PBV.xlsx",
    "Payables-Turnover.xlsx",
]
